//! Generates the built-in FIGlet font table by scanning `assets/figlet/`.
//!
//! A hand-written table would have to be updated every time a font is added or
//! removed, and a typo in a filename would only surface at runtime as a missing
//! font. Scanning at build time keeps the table and the directory in sync.

use std::{env, fs, path::Path};

fn main() {
    // The executable's icon. Windows reads it from the PE resources, so it has
    // to be linked in rather than loaded at runtime like the window icon.
    #[cfg(windows)]
    {
        use embed_resource::CompilationResult;

        println!("cargo:rerun-if-changed=assets/icon/icon.ico");
        println!("cargo:rerun-if-changed=assets/icon/app.rc");

        match embed_resource::compile("assets/icon/app.rc", embed_resource::NONE) {
            // An icon is cosmetic and a machine without a resource compiler can
            // still build the program, but saying so beats a mystery.
            CompilationResult::NotAttempted(reason) => {
                println!("cargo:warning=no resource compiler ({reason}); the executable will have no icon");
            }
            // This one is not cosmetic: the .rc is wrong, and the build would
            // quietly produce an executable with no icon at all.
            CompilationResult::Failed(reason) => {
                panic!("failed to embed the application icon: {reason}");
            }
            CompilationResult::Ok | CompilationResult::NotWindows => {}
        }
    }

    let dir = Path::new("assets/figlet");
    println!("cargo:rerun-if-changed=assets/figlet");

    let mut names = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "flf") {
                if let Some(stem) = path.file_stem() {
                    names.push(stem.to_string_lossy().into_owned());
                }
            }
        }
    }
    names.sort();

    // `include_str!` inside the generated file resolves relative to *that* file,
    // which lives in OUT_DIR, so the path has to be anchored at the manifest dir.
    let mut out = String::from("// @generated by build.rs — do not edit\n");
    out.push_str("pub static BUILTIN_FONTS: &[(&str, &str)] = &[\n");
    for name in &names {
        out.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/figlet/{name}.flf\"))),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    fs::write(Path::new(&out_dir).join("fonts_generated.rs"), out)
        .expect("failed to write generated font table");
}
