//! fastfetch configuration export.
//!
//! fastfetch reads a logo from a plain text file and honours the ANSI escapes
//! inside it, so the artwork itself is covered by the ANSI exporter. What this
//! adds is the other half of the job: a config that points at that file, with
//! the settings that are not obvious and are annoying to discover.
//!
//! The output is JSONC — JSON with comments — which is what fastfetch's own
//! generated config uses, and which lets the file explain itself.

use crate::export::Options;
use crate::model::Artwork;

pub fn export(art: &Artwork, opts: &Options) -> String {
    let logo_file = &opts.logo_source;
    let uses_background = art.cells.iter().flatten().any(|c| c.bg.is_some());

    let mut out = String::new();
    out.push_str("// fastfetch configuration, generated by wart.\n");
    out.push_str("//\n");
    out.push_str("// Two ways to use this:\n");
    out.push_str("//   1. On its own:  fastfetch --config <this file>\n");
    out.push_str("//   2. Merged:      copy the \"logo\" block below into\n");
    out.push_str("//                   ~/.config/fastfetch/config.jsonc\n");
    out.push_str("//\n");
    out.push_str(&format!(
        "// Either way, keep {logo_file} next to this file, or make \"source\"\n\
         // an absolute path.\n"
    ));
    out.push_str("//\n");
    out.push_str("// The logo is read as text, so the colours in it need a terminal\n");
    out.push_str("// with truecolor:  export COLORTERM=truecolor\n");

    if uses_background {
        // Worth spelling out: a logo that looks right in the preview can come
        // out wrong here, and the cause is not obvious.
        out.push_str("//\n");
        out.push_str("// WARNING: this artwork sets background colours — it uses half\n");
        out.push_str("// blocks or a filled background. fastfetch draws the logo as text\n");
        out.push_str("// and does not always honour background colours, so some terminals\n");
        out.push_str("// will show it differently from the preview. If that happens,\n");
        out.push_str("// re-export in a style that only sets the foreground colour.\n");
    }
    out.push('\n');

    out.push_str("{\n");
    out.push_str(
        "  \"$schema\": \"https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json\",\n",
    );
    out.push('\n');

    out.push_str("  \"logo\": {\n");
    out.push_str("    // \"file\" reads the escaped text as-is, which is what we want.\n");
    out.push_str("    \"type\": \"file\",\n");
    out.push_str(&format!("    \"source\": \"{logo_file}\",\n"));
    out.push_str("    \"position\": \"left\",\n");
    out.push_str("    // Right padding is the gap between the logo and the text.\n");
    out.push_str("    // Raise it if a wide logo crowds the information column.\n");
    out.push_str("    \"padding\": { \"top\": 1, \"left\": 2, \"right\": 6 }\n");
    out.push_str("  },\n");
    out.push('\n');

    out.push_str("  \"display\": {\n");
    // A logo wide enough to reach the last column would otherwise wrap and
    // scatter itself down the terminal.
    out.push_str("    // Stop fastfetch wrapping a wide logo onto the next line.\n");
    out.push_str("    \"disableLinewrap\": true,\n");
    out.push_str("    \"separator\": \": \"\n");
    out.push_str("  },\n");
    out.push('\n');

    out.push_str("  // A starting set. Delete what you do not want, or run\n");
    out.push_str("  // `fastfetch --gen-config` and merge this file's \"logo\" block in.\n");
    out.push_str("  \"modules\": [\n");
    for module in ["title", "os", "kernel", "shell", "terminal", "cpu", "gpu", "memory"] {
        out.push_str(&format!("    \"{module}\",\n"));
    }
    // Drop the trailing comma: JSONC allows it, but keeping the file strictly
    // valid JSON means it can be pasted anywhere without a second thought.
    out.truncate(out.trim_end().len() - 1);
    out.push('\n');
    out.push_str("  ]\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Cell, Rgb};

    fn opts(name: &str) -> Options {
        Options {
            logo_name: name.to_owned(),
            logo_source: format!("{name}.txt"),
            ..Default::default()
        }
    }

    fn plain() -> Artwork {
        Artwork::from_lines(["ab"])
    }

    #[test]
    fn the_output_is_valid_json_once_comments_are_stripped() {
        // JSONC is a superset, but the result should still be plain JSON so it
        // can be pasted anywhere.
        let text = export(&plain(), &opts("logo"));
        let stripped: String = text
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: serde_json::Value =
            serde_json::from_str(&stripped).expect("the config should be valid JSON");
        assert!(parsed.get("logo").is_some());
        assert!(parsed.get("modules").is_some());
    }

    #[test]
    fn it_points_at_the_logo_file_by_the_name_it_was_given() {
        let text = export(&plain(), &opts("wart-logo"));
        assert!(text.contains("\"source\": \"wart-logo.txt\""), "got:\n{text}");
    }

    #[test]
    fn it_does_not_warn_for_a_foreground_only_artwork() {
        assert!(!export(&plain(), &opts("logo")).contains("WARNING"));
    }

    #[test]
    fn it_warns_when_the_artwork_uses_background_colours() {
        let art = Artwork {
            cells: vec![vec![Cell {
                ch: '▀',
                fg: Some(Rgb::new(1, 2, 3)),
                bg: Some(Rgb::new(4, 5, 6)),
            }]],
        };
        let text = export(&art, &opts("logo"));
        assert!(text.contains("WARNING"), "a background colour should be flagged");
        assert!(text.contains("half"), "the warning should say why");
    }

    #[test]
    fn it_explains_how_to_use_the_file() {
        let text = export(&plain(), &opts("logo"));
        assert!(text.contains("--config"), "should show the direct invocation");
        assert!(text.contains("config.jsonc"), "should mention merging");
    }
}
